### ISSUE TITLE
Allow Tooltip to follow mouse cursor

### ISSUE THREAD

**Issue by zpfdev** [bumbeishvili/d3-v6-tip#10]
https://jsfiddle.net/2ukpa84c/5/

In this example, I have a zoomable and draggable map. By double clicking the map, you zoom in. However, the tooltip position still stays the same, so if you zoomed-in, you can't' see the tooltip anymore. Also the tooltip doesn't seem to be in the right position. For example, when hover over an element on the map, the tooltip will show up on the area of other elements.

The problem I am facing is similar to this [issue](https://github.com/bumbeishvili/d3-v6-tip/issues/7)

Is there a way to configure that?

**Comment by bumbeishvili** [comment]
You can just call tip.show() in `zoom` handler

https://jsfiddle.net/n38qu7vm/


https://user-images.githubusercontent.com/6873202/122399688-11723300-cf8c-11eb-9923-b694aaeac3bb.mp4

**Comment by zpfdev** [comment]
@bumbeishvili Thank you.
