### ISSUE TITLE
Can't specify rootElement using npm import

### ISSUE THREAD

**Issue by mattiaerli97** [bumbeishvili/d3-v6-tip#5]
I'm using NPM and installed the 1.0.8 version of d3-v6-tip. I'm trying to specify a different element where I can append the tooltip (for style reasons), but it's still attaching to the document body.

The code I'm using is this
```
this.tip = d3tip()
      .attr('class', 'd3-tip')
      .rootElement(document.getElementById('graph'))
      .html((EVENT, d) => d.tooltip.replace('_x', d.x).replace('_y', d.y))
```

but I'm receiving the following error 
```
index.js:157 Uncaught TypeError: Object(...)(...).attr(...).rootElement is not a function
```

Can you please help me? I don't want to load this library as a standalone library, so I'm trying this road. Thank you very much

**Comment by bumbeishvili** [comment]
There is no such method  `rootElement` in the API and nor it is planned to be added. 

Not sure about your reasons though, can you elaborate more? What styling reasons you mean?

**Comment by mattiaerli97** [comment]
The reasons aren't important I think. The problem is that in your library you declare the following code
```
var direction = d3_tip_direction,
        offset = d3_tip_offset,
        html = d3_tip_html,
        node = initNode(),
        svg = null,
        point = null,
        target = null

    function tip(vis) {
        svg = getSVGNode(vis)
        point = svg.createSVGPoint()
        document.body.appendChild(node)
    }

```

While in the original tip library the code is this

```
var direction   = d3TipDirection,
        offset      = d3TipOffset,
        html        = d3TipHTML,
        rootElement = document.body,
        node        = initNode(),
        svg         = null,
        point       = null,
        target      = null

    function tip(vis) {
      svg = getSVGNode(vis)
      if (!svg) return
      point = svg.createSVGPoint()
      rootElement.appendChild(node)
    }
```
With this problem, I can't specify a custom rootElement.
The style areasons are only for my personal file organization, so I can put scss in the same component I attach the tooltip

**Comment by bumbeishvili** [comment]
Interesting - I think it was removed at the second iteration of this library

https://github.com/cgav/d3-tip/blob/master/src/index.js

Here is a history

<img width="644" alt="Screenshot 2021-05-18 at 17 24 36" src="https://user-images.githubusercontent.com/6873202/118658984-f336dd00-b7fd-11eb-8dfc-7c56e1c97a66.png">

Currently, I am not sure about that method, I don't know how it works, and nor I have time to check it deeply

**Comment by bumbeishvili** [comment]
If you can find a time to fix this issue, please create a PR and include working example so I can check it as well and if everything  will look all right, I will merge it

**Comment by mattiaerli97** [comment]
ok I wil open a PR with the working example, hoping to help your project 😄

**Comment by bumbeishvili** [comment]
To be honest, I don't consider this project mine, my part will be less than 1 %, compared to the whole effort

**Comment by mattiaerli97** [comment]
I don't know hot to attach a working example, as in a JSFiddle I can only import the actual version of the d3-v6-tip package. Have you got any idea on how to make this? Thanks
